services:
  icds-frontend:
    image: ghcr.io/nmcc1212/icds-frontend:v3
    ports:
      - "3000:3000"
    container_name: icds-frontend
    environment:
      - API_URL=http://nial.netbuildertraining.com/api
      - MONGO_URI=mongodb://db:27017/socialAPI
      - AUTH0_SECRET=${AUTH0_SECRET}
      - AUTH0_BASE_URL=${AUTH0_BASE_URL}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
  db:
    image: mongo
    container_name: db
    hostname: db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./mongo/socialAPI.posts.json:/docker-entrypoint-initdb.d/socialAPI.posts.json:ro

volumes:
  mongo-data:
