services:
  icds-frontend:
    image: ghcr.io/nmcc1212/icds-frontend:v2
    ports:
      - "3000:3000"
    container_name: icds-frontend
    environment:
      - API_URL=${API_URL}
      - MONGO_URI=${MONGO_URI}
      - AUTH0_SECRET=${AUTH0_SECRET}
      - AUTH0_BASE_URL=${AUTH0_BASE_URL}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
    depends_on:
      - db

  db:
    image: mongo
    container_name: db
    hostname: db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      # - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      # - ./mongo/socialAPI.posts.json:/docker-entrypoint-initdb.d/socialAPI.posts.json:ro

volumes:
  mongo-data:
