services:
  icds-frontend:
    image: ghcr.io/nmcc1212/icds-frontend:v2
    ports:
      - "3000:3000"
    container_name: icds-frontend
    environment:
      - API_URL=${API_URL}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - db

  db:
    image: mongo
    container_name: db
    hostname: db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo/initv1.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./mongo/v1.socialAPI.posts.json:/docker-entrypoint-initdb.d/v1.socialAPI.posts.json:ro
      - ./mongo/v1.socialAPI.users.json:/docker-entrypoint-initdb.d/v1.socialAPI.users.json:ro

volumes:
  mongo-data:
